export const OVERFLOW_HIDDEN:string = 'hidden'
export const OVERFLOW_X_HIDDEN:string = 'hidden'
export const HALYAVA_PROMO_CODE:string = 'HALYAVA'
export const BEVERAGE_PROMO_CODE:string = 'BEVERAGE'
export const DONER_PROMO_CODE:string = 'DONER'
export const DELETE:string = 'Backspace'
export const SHIPPING_FEE = 2.5
export const PRODUCTS_BEGIN = 1
export const PRODUCTS_END = 17
export const BEVERAGE_BEGIN = 10
export const DONER_BEGIN = 4
export const DONER_END = 9
export const THIRD_ELEMENT = 2
export const BONUS_COEFFICIENT=0.01
export const ZERO=0
export const FOUR = 4
export const SIX = 6
